"""
salome_generator.py
===================
Générateur de dump Salomé — Nuage de points 3D
Conversion de l'outil Tkinter original vers Streamlit.

Lancement :
    streamlit run salome_generator.py
"""

import streamlit as st
import numpy as np
import plotly.graph_objects as go
import io
import os

# ──────────────────────────────────────────────────────────────────────────────
# 1. PARSING DU FICHIER DE POINTS
# ──────────────────────────────────────────────────────────────────────────────

def parse_points(content: str) -> tuple[list, list, list]:
    """
    Parse le contenu texte d'un fichier de points CloudCompare.
    Ignore la première ligne (header) et ne garde que X, Y, Z.

    Returns
    -------
    (x, y, z) : trois listes de floats
    """
    x, y, z = [], [], []
    lines = content.splitlines()
    for line in lines[1:]:       # skip header
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            x.append(float(parts[0]))
            y.append(float(parts[1]))
            z.append(float(parts[2]))
        except ValueError:
            continue
    return x, y, z


# ──────────────────────────────────────────────────────────────────────────────
# 2. GÉNÉRATION DU SCRIPT SALOMÉ
# ──────────────────────────────────────────────────────────────────────────────

def generate_salome_script(x: list, y: list, z: list, nom: str) -> str:
    """
    Génère le contenu du fichier .py compatible Salomé.

    Parameters
    ----------
    x, y, z : coordonnées des points
    nom     : nom de base du fichier (sans extension)

    Returns
    -------
    str : contenu complet du script Python Salomé
    """
    lines = []

    # En-tête
    lines += [
        "#!/usr/bin/env python\n",
        "###\n",
        f"### Generated by Salomé Generator — {nom}\n",
        "###\n",
        "import sys\n",
        "import salome\n",
        "salome.salome_init()\n",
        "import salome_notebook\n",
        "notebook = salome_notebook.NoteBook()\n",
        "###\n",
        "### GEOM component\n",
        "###\n",
        "import GEOM\n",
        "from salome.geom import geomBuilder\n",
        "import math\n",
        "import SALOMEDS\n",
        "geompy = geomBuilder.New()\n",
        "O  = geompy.MakeVertex(0, 0, 0)\n",
        "OX = geompy.MakeVectorDXDYDZ(1, 0, 0)\n",
        "OY = geompy.MakeVectorDXDYDZ(0, 1, 0)\n",
        "OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)\n",
    ]

    # Vertices
    for i, (xi, yi, zi) in enumerate(zip(x, y, z), 1):
        lines.append(f"Vertex_{i} = geompy.MakeVertex({xi}, {yi}, {zi})\n")
        lines.append(f"geompy.addToStudy(Vertex_{i}, 'Vertex_{i}')\n")

    # Pied de page
    lines += [
        "geompy.addToStudy( O,  'O'  )\n",
        "geompy.addToStudy( OX, 'OX' )\n",
        "geompy.addToStudy( OY, 'OY' )\n",
        "geompy.addToStudy( OZ, 'OZ' )\n",
        "if salome.sg.hasDesktop(): salome.sg.updateObjBrowser()\n",
        "### Fin du script\n",
    ]

    return "".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# 3. GRAPHIQUE 3D
# ──────────────────────────────────────────────────────────────────────────────

def plot_3d(x: list, y: list, z: list) -> go.Figure:
    """
    Retourne une figure Plotly du nuage de points 3D.
    """
    fig = go.Figure(data=[go.Scatter3d(
        x=x, y=y, z=z,
        mode="markers",
        marker=dict(
            size=2,
            color=z,
            colorscale="Viridis",
            opacity=0.8,
            colorbar=dict(title="Z"),
        ),
    )])

    fig.update_layout(
        scene=dict(
            xaxis_title="X",
            yaxis_title="Y",
            zaxis_title="Z",
            aspectmode="data",
        ),
        margin=dict(l=0, r=0, t=40, b=0),
        title="Nuage de points 3D",
        height=600,
        template="plotly_white",
    )
    return fig


# ──────────────────────────────────────────────────────────────────────────────
# 4. INTERFACE STREAMLIT
# ──────────────────────────────────────────────────────────────────────────────

BANNER = """
```
         ====
      ========
   +============
=================:
= ===============-
===.==========: ===        ======  ======.      +++++++-     ++     ++    =+
==== ======. ======            ==  ==::-===     ++::....    =++.    ++    =+
+===== =  +========           =+   ==    -=:    ++          ++++    ++    =+
+ =====.===========          ==    ==     ==    ++         .+  +    ++    =+
++-====.=+-=======          ====   ==     ==    +++++++    ++  ++   ++    =+
++.====: ++++ :+= +            ==  ==     ==    ++         +   :+   ++    =+
+++.===.+++++++++++             =  ==     ==    ++        ++++++++  ++    ++
++++.:-:+++++++++++       .=   +=  ==   :==     ++        +:    ++  ++-  :++
+++++++:+++++++++++        =====:  =======      ++++++++ ++      ++  ++++++
+++++++:+++++++++++
 ++++++:+++++++++++
   ++++:++++++++
    =++:+++++
      +:++
```
"""


def main():
    st.set_page_config(
        page_title="Générateur dump Salomé",
        page_icon="🔷",
        layout="wide",
    )

    # ── En-tête ───────────────────────────────────────────────────────────────
    st.title("🔷 Générateur de dump Salomé — Nuage de points 3D")
    st.markdown("Fait avec ♥ par Thibaud*")

    with st.expander("📟 Logo ASCII", expanded=False):
        st.code(BANNER, language=None)

    st.markdown("---")

    # ── Instructions ──────────────────────────────────────────────────────────
    with st.expander("📋 Mode d'emploi", expanded=True):
        st.markdown(
            """
1. **Enregistrer** les points au format `.txt` depuis CloudCompare ;
2. **Charger** le fichier avec le bouton ci-dessous ;
3. Le script `.py` Salomé est généré et téléchargeable directement ;
4. **Ouvrir** ce fichier dans Salomé via un dump (`Ctrl + T` dans Salomé).

> ⚠️ **Attention** : si plus de 5 000 points, Salomé peut avoir des difficultés
> à importer le dump et corrompre la géométrie. Un avertissement s'affiche au-delà
> de 2 000 points.

            """
        )

    # ── Upload ────────────────────────────────────────────────────────────────
    uploaded = st.file_uploader(
        "📂 Sélectionner un fichier de points (.txt)",
        type=["txt"],
        help="Fichier exporté depuis CloudCompare — format : X Y Z (+ colonnes optionnelles ignorées)",
    )

    if uploaded is None:
        st.info("En attente d'un fichier…")
        return

    # ── Parsing ───────────────────────────────────────────────────────────────
    content = uploaded.read().decode("utf-8", errors="replace")
    x, y, z = parse_points(content)
    n = len(x)

    if n == 0:
        st.error("Aucun point valide trouvé dans le fichier. Vérifier le format (X Y Z par ligne).")
        return

    # ── Info points ───────────────────────────────────────────────────────────
    if n > 2000:
        st.warning(
            f"⚠️ **{n} points détectés** : quantité importante, "
            "Salomé risque d'avoir des difficultés à importer le dump."
        )
    else:
        st.success(f"✅ **{n} points détectés** : quantité raisonnable, import Salomé sans risque particulier.")

    # ── Statistiques rapides ──────────────────────────────────────────────────
    with st.expander("📊 Statistiques du nuage", expanded=False):
        col1, col2, col3 = st.columns(3)
        for col, vals, label in zip([col1, col2, col3], [x, y, z], ["X", "Y", "Z"]):
            col.metric(f"{label} min", f"{min(vals):.4f}")
            col.metric(f"{label} max", f"{max(vals):.4f}")
            col.metric(f"{label} étendue", f"{max(vals) - min(vals):.4f}")

    # ── Graphique 3D ─────────────────────────────────────────────────────────
    st.subheader("📊 Visualisation 3D")
    fig = plot_3d(x, y, z)
    st.plotly_chart(fig, use_container_width=True)

    # ── Génération du script Salomé ───────────────────────────────────────────
    st.subheader("⚙️ Script Salomé généré")
    nom = os.path.splitext(uploaded.name)[0]
    script = generate_salome_script(x, y, z, nom)

    nb_lignes = script.count("\n")
    st.markdown(f"Script généré : **{nb_lignes} lignes**, **{n} vertices**.")

    with st.expander("👁️ Aperçu du script (50 premières lignes)", expanded=False):
        preview = "\n".join(script.splitlines()[:50]) + "\n..."
        st.code(preview, language="python")

    # ── Téléchargement ────────────────────────────────────────────────────────
    st.download_button(
        label="📥 Télécharger le script Salomé (.py)",
        data=script.encode("utf-8"),
        file_name=f"{nom}.py",
        mime="text/x-python",
        use_container_width=True,
        type="primary",
    )

    st.markdown("---")
    st.caption("Générateur de dump Salomé · CloudCompare → Salomé GEOM · 🔷")


if __name__ == "__main__":
    main()
